name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web assets
      run: npm run build
      
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug
        cd ..
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk